[package]
name = "zo-abi"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.20.1"
bytemuck = "1"
fixed = "1.9"
